/**
 * Data Transfer Object (DTO) representing the server response payload for a chat interaction.
 */
export interface ChatResponse {
    /**
     * The textual content generated by the assistant or server response.
     */
    readonly content: string;

    /**
     * Immutable key-value record containing supplementary metadata returned by the API.
     */
    readonly metadata: Readonly<Record<string, unknown>>;
}