import { createChatRepository } from "@/application/repositories/createChatRepository";
import { SendConversationUseCase } from "@/domain/usecases/SendConversationUseCase";

/**
 * Factory function that creates and returns an instance of the {@link SendConversationUseCase}.
 * Injects a concrete ChatRepository implementation generated by the repository factory.
 *
 * @returns A fully configured SendConversationUseCase instance ready for execution.
 */
export function createSendConversationUseCase(): SendConversationUseCase {
    return new SendConversationUseCase(
        createChatRepository(),
    );
}